### ISSUE TITLE
feature-request: delete altbot-post by liking

### ISSUE THREAD

**Issue by Schoeneh** [micr0-dev/AltBot#9]
I'm thinking of a functionality akin to https://botsin.space/@PleaseCaption:
> This toot's media doesn't have descriptions, please add some next time! 🤳 
> Not too late to edit and add captions. 
> ⭐ Favourite this toot to delete it.

See https://github.com/zoetrope69/please-caption-mastodon

**Comment by Schoeneh** [comment]
My experience with ~2yrs of caption-bot: I've never accidentally deleted a post :)

But yeah, it could be an issue...
Maybe via a reply "thanks" to delete?

**Comment by micr0-dev** [comment]
hmm, i get it but also i think that deleting its messages shouldn't be like a normal thing, for transparency sake, so that people can see that altbot was used. I was thinking specifically in case somehow some sorta sensitive info got into the message and the person wants to delete it,

now that i think about it, the est way to do this would be to delete the altbot post if the original post is deleted

**Comment by Schoeneh** [comment]
> The presence of a reply serves as an indicator that AltBot was used to generate alt-text using AI.
Imo this is a very valid reason to not implement a general 'delete'-function & I rescind my original feature-request :)
